#!/bin/bash

# testkademlia address firsthost nodeid inputfile outputfile logfile
# passes inputfile one line at a time to kademlia
# if the line is sleep n, the sleep command is called instead of passing the command to kademlia
# stdout and stderr are sent to outputfile
# inputfile must end with quit and a newline or kademlia will never terminate

while read input
do 
	if [[ $input =~ ^sleep ]]
	then
		$input
	else
		echo "$input"
	fi

done < $4 | ../bin/main $1 $2 $3 1>$5 2>$6
